# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcptask_runner" do
  version "0.3.31"

  on_macos do
    on_intel do
      sha256 "245fc70620696b23a8e0a870fcec467830f356139bae96ab4450b6a143a5e32e"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab4d656cae9055d1e595f9db03f80fd818ea5f5538e8f67c70daa0500c66034c"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4ed6bfd942200af5f1cd6823bb82c75a4088b735e04c165465352fe6c18c969"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48b3063bf9ab2c1d1a699db4291182b68c234aaead4a7510de57641115e34fd0"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mcptask_runner"
  desc "Drives Claude Code through the tasks on mcptask.online"
  homepage "https://mcptask.online"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcptask_runner"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcptask_runner"]
    end
  end

  # No zap stanza required

end
