# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcptask_runner" do
  version "0.3.13"

  on_macos do
    on_intel do
      sha256 "0cd1ebadd19a66ffbb1faaff791b4afa6f66f15b2683d9d43c7f2578a03d0ec6"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aebbe7a5546ad2e6aa9159643f322b7a209d502b7f94f66753dfd4b5bd343e2b"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6656c999f5562ecc7d29e670d2a0fa4bc0411a3a5108b2fd95d826757fc5c951"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4494f16228dd3211c2303ba49791e3947fe64a60fd76525053b42af8ee06dc0"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mcptask_runner"
  desc "Drives Claude Code through the tasks on mcptask.online"
  homepage "https://mcptask.online"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcptask_runner"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcptask_runner"]
    end
  end

  # No zap stanza required

end
