# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcptask_runner" do
  version "0.3.20"

  on_macos do
    on_intel do
      sha256 "aba303897def3cd73800bb944a34f44339afc42249f2a03fbd2ee4e1c9cbdb7e"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c68fa911ca78cbc984dd3aaff1d03a77f350e0c07c1752445ff08253855ecea4"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a5327509d395a84b87357e8638227fb0a0360d9e77ec861a0d1aaceac5c8a50c"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "018d63a20b226bfc94a045120cc0ba5b11f1bbbb13b5edd4b744d8f6c3efb83e"
      url "https://github.com/jchsoft/mcptask-releases/releases/download/v#{version}/mcptask_runner_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mcptask_runner"
  desc "Drives Claude Code through the tasks on mcptask.online"
  homepage "https://mcptask.online"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcptask_runner"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcptask_runner"]
    end
  end

  # No zap stanza required

end
